// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire_lx

// Injectors from wire.go:

//func InitializeEvent() (Event, error) {
//	message := NewMessage()
//	greeter := NewGreeter(message)
//	event, err := NewEvent(greeter)
//	if err != nil {
//		return Event{}, err
//	}
//	return event, nil
//}
